#webservices
server.port=8010
spring.application.name=ecouture-services

#database
spring.datasource.url=jdbc:postgresql://46.250.226.123:5432/ecouturedb
spring.datasource.username=emma
spring.datasource.password=secret123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#healhtcheck
management.endpoints.web.exposure.include=health,info

spring.jpa.open-in-view=false


security
spring.security.oauth2.client.registration.github.client-id=Ov23liAguyPXsIlyUjGz
spring.security.oauth2.client.registration.github.client-secret=da3d9d961a5ff5e383d80e759deb4832963ca084
spring.security.oauth2.client.registration.github.scope=read:user,user:email

spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=id

#jwt
app.jwt.secret=yXq5kRUylOpuViPTWzApzxUnF9Hl6BWPjp8l08AVbvc=
app.jwt.expiration-ms=86400000

